function [spider_vids, heights_vids, pain_stim] = TrialSplit2()

    spider_vids = ["Spider_1.mp4",...
                    "Spider_2.m4v",...
                    "Spider_3.mp4",...
                    "Spider_4.mov",...
                    "Spider_5.m4v",...
                    "Spider_6.mov",...
                    "Spider_7.mov",...
                    "Spider_8.m4v",...
                    "Spider_9.mp4",...
                    "Spider_10.mp4",...
                    "Spider_11.mp4",...
                    "Spider_12.mp4",...
                    "Spider_13.mp4",...
                    "Spider_14.mp4",...
                    "Spider_15.m4v",...
                    "Spider_16.mp4",...
                    "Spider_17.mp4",...
                    "Spider_18.mov",...
                    "Spider_19.mov",...
                    "Spider_20.mp4"...
                    %"Spider_21.m4v",...
                    %"Spider_22.m4v",...
                    %"Spider_23.mp4",...
                    %"Spider_24.m4v",...      
        ];
    
    heights_vids = ["Heights_1.mp4",...
                    "Heights_2.mp4",...
                    "Heights_3.m4v",...
                    "Heights_4.mp4",...
                    "Heights_5.mov",...
                    "Heights_6.mp4",...
                    "Heights_7.mp4",...
                    "Heights_8.m4v",...
                    "Heights_9.mov",...
                    "Heights_10.m4v",...
                    "Heights_11.mov",...
                    "Heights_12.mp4",...
                    "Heights_13.mp4",...
                    "Heights_14.mp4",...
                    "Heights_15.mp4",...
                    "Heights_16.m4v",...
                    "Heights_17.mp4",...
                    "Heights_18.m4v",...
                    "Heights_19.m4v",...
                    "Heights_20.mp4"...
%                     "Heights_21.m4v",...
%                     "Heights_22.mp4",...
%                     "Heights_23.mov",...
%                     "Heights_24.m4v",...
        ];
    
    pain_low = normrnd(2,.5,10,1);
    pain_high = normrnd(6,.5,10,1);
    pain_stim = sort([pain_low;pain_high]);
    pain_stim = string(pain_stim);
    
    heights_vids = flip(heights_vids);
    spider_vids = flip(spider_vids);

end