function [spider_vids, heights_vids, pain_stim] = TrialSplit2()

    spider_vids = ["spider_01.m4v",...
                    "spider_02.mov",...
                    "spider_03.m4v",...
                    "spider_04.m4v",...
                    "spider_05.mov",...
                    "spider_06.m4v",...
                    "spider_07.mov",...
                    "spider_08.m4v",...
                    "spider_09.mov",...
                    "spider_10.m4v",...
                    "spider_11.m4v",...
                    "spider_12.mov",...       
        ];
    
    heights_vids = ["heights_01.m4v",...
                    "heights_02.m4v",...
                    "heights_03.mov",...
                    "heights_04.m4v",...
                    "heights_05.m4v",...
                    "heights_06.m4v",...
                    "heights_07.m4v",...
                    "heights_08.mov",...
                    "heights_09.m4v",...
                    "heights_10.m4v",...
                    "heights_11.mov",...
                    "heights_12.mov",...
        ];
    
    pain_low = normrnd(2,.5,6,1);
    pain_high = normrnd(6,.5,6,1);
    pain_stim = sort([pain_low;pain_high]);
    pain_stim = string(pain_stim);

end